### ISSUE TITLE
Clarify documentation

### ISSUE THREAD

**Issue by NoelOConnell** [indeedeng/indeedeng.github.io#1]
Hi,

While reading your documentation for XML feed I noticed some issues.
http://opensource.indeedeng.io/api-documentation/docs/xml-feed-ia/#including-screener-questions

There is a table which lists the parameters that can be used when adding screener questions to the XML feed. On this table the **Question** field is marked as required.

However when looking at the example question for **file** and **information** they use the **text** property and not **question**.

Can you clarify if **question** is not required for those field types and to use **text** instead?

Same issue applies to **pagebreak** but I'm not using that field.

Thanks

**Comment by tate-indeed** [comment]
Hello Neal,
I've opened an internal ticket to clarify this with our developers, and will update the documentation accordingly. Thanks.

**Comment by tate-indeed** [comment]
*Noel, not Neal, sorry about that

**Comment by NoelOConnell** [comment]
@tate-indeed any clarification on the documentation?

**Comment by tate-indeed** [comment]
Noel, 
I've just received some clarification from internal devs and will be working to update the documentation accordingly. That might not merge in until next week, so in the meantime, here is the information I've received:

- For "File" type questions, the **question field is required** but the text field is not
- For "Information" type questions, the **text field is required** but the question field is not
- For "Page Break" type questions, neither is required

Does this clarify things for you? Again, we'll update the documentation to reflect this but I wanted to get you the info more quickly.

**Comment by NoelOConnell** [comment]
Thanks for the clarification, that is great.

We will be making those adjustments to the feed in the coming days.

**Comment by tate-indeed** [comment]
@NoelOConnell these changes are now live in the documentation. Thanks for pointing this out to us and helping us improve it!
